Check for byteswap.h existence for src/f2fs/f2fs_fs.h
src/f2fs/f2fs_fs.h uses bswap_64(), which is part of byteswap.h e.g.
on glibc-based systems. The src/f2fs/f2fs_fs.h already knows how to
handle the existence of byteswap.h, once there is a configure header
check for it. Otherwise building on s390x fails like this:

f2fs/f2fs_fs.h:218:25: error: implicit declaration of function ‘bswap_64’; did you mean ‘bswap_32’? [-Wimplicit-function-declaration]