Add missing declarations.
main.c:314: warning: implicit declaration of function 'get_image_bitmap'
main.c:642: warning: implicit declaration of function 'write_last_block'